import Head from 'next/head'
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>First myNext.Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <Navbar/>
        <h1 className="font-bold">HomePage</h1>
      </body>
      
    </div>
  )
}
